export const PROMPTS = [
  "The worst thing to hear from your GPS",
  "A rejected name for a luxury candle",
  "The real reason the dinosaurs disappeared",
  "A terrible slogan for a dentist",
  "Something you should never whisper on an elevator",
  "The least inspiring fortune cookie message",
  "A strange thing to keep in your glove box",
  "The title of a cooking show hosted by a toddler",
  "A bad name for a superhero's sidekick",
  "The last thing you want your smart fridge to say",
  "An unusual Olympic event that would guarantee a gold medal",
  "A suspicious item on a hotel breakfast buffet",
  "The first rule of a very boring secret society",
  "A phrase that should never end with ‘trust me’",
  "The worst possible theme for a birthday party",
  "A tiny hill someone would absolutely die on",
  "Something a ghost does when nobody is home",
  "The rejected eighth wonder of the world",
  "A product that definitely should not be voice activated",
  "The true purpose of the little pocket on jeans",
  "A surprising thing to find at the bottom of a cereal box",
  "The worst name for a Wi-Fi network",
  "A new holiday nobody asked for",
  "The first sentence in a pirate's dating profile",
];
